function plotConfusionMat(csvFilePath, customTitle)
data = readtable(csvFilePath);

actualValues = data.ActualGesture;
predictedDQN = data.predDQN;
predictedDDQN = data.predDDQN;

postPredictedDQN = data.postDQN;
postPredictedDDQN = data.postDDQN;

[cfDQN, orderDQN] = confusionmat(actualValues, predictedDQN);
[cfDDQN, orderDDQN] = confusionmat(actualValues, predictedDDQN);

[cfPostDQN, orderPostDQN] = confusionmat(actualValues, postPredictedDQN);
[cfPostDDQN, orderPostDDQN] = confusionmat(actualValues, postPredictedDDQN);

uniqueValues = unique(vertcat(actualValues, predictedDQN, predictedDDQN));
actionLabels = cell(size(uniqueValues));

for i = 1:length(uniqueValues)
    actionLabels{i} = mapAction(uniqueValues(i));
end

allLabels = cellfun(@(x) x{1}, actionLabels, 'UniformOutput', false);

classMetrics(cfDQN, orderDQN, allLabels, "cmDQN-" + customTitle + ".csv");
classMetrics(cfDDQN, orderDDQN, allLabels, "cmDDQN-" + customTitle + ".csv");

classMetrics(cfPostDQN, orderPostDQN, allLabels, "cmPostDQN-" + customTitle + ".csv");
classMetrics(cfPostDDQN, orderPostDDQN, allLabels, "cmPostDDQN-" + customTitle + ".csv");

figure('WindowState', 'maximized');

subplot(2, 2, 1);
confusionchart( ...
    cfDQN, ...
    allLabels, ...
    'Title', "DQN " + customTitle, ...
    'FontSize', 24, ...
    'ColumnSummary','column-normalized', ...
    'RowSummary','row-normalized');

set(gca, 'FontSize', 16);

subplot(2, 2, 2);
confusionchart( ...
    cfDDQN, ...
    allLabels, ...
    'Title', "DDQN " + customTitle, ...
    'FontSize', 24, ...
    'ColumnSummary','column-normalized', ...
    'RowSummary','row-normalized');

set(gca, 'FontSize', 16);

subplot(2, 2, 3);
confusionchart( ...
    cfPostDQN, ...
    allLabels, ...
    'Title', "Post-processing DQN " + customTitle, ...
    'FontSize', 24, ...
    'ColumnSummary','column-normalized', ...
    'RowSummary','row-normalized');

set(gca, 'FontSize', 16);

subplot(2, 2, 4);
confusionchart( ...
    cfPostDDQN, ...
    allLabels, ...
    'Title', "Post-processing DDQN " + customTitle, ...
    'FontSize', 24, ...
    'ColumnSummary','column-normalized', ...
    'RowSummary','row-normalized');

set(gca, 'FontSize', 16);
end
